require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ModeradorsController do

  # This should return the minimal set of attributes required to create a valid
  # Moderador. As you add validations to Moderador, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "nome" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ModeradorsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all moderadors as @moderadors" do
      moderador = Moderador.create! valid_attributes
      get :index, {}, valid_session
      assigns(:moderadors).should eq([moderador])
    end
  end

  describe "GET show" do
    it "assigns the requested moderador as @moderador" do
      moderador = Moderador.create! valid_attributes
      get :show, {:id => moderador.to_param}, valid_session
      assigns(:moderador).should eq(moderador)
    end
  end

  describe "GET new" do
    it "assigns a new moderador as @moderador" do
      get :new, {}, valid_session
      assigns(:moderador).should be_a_new(Moderador)
    end
  end

  describe "GET edit" do
    it "assigns the requested moderador as @moderador" do
      moderador = Moderador.create! valid_attributes
      get :edit, {:id => moderador.to_param}, valid_session
      assigns(:moderador).should eq(moderador)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Moderador" do
        expect {
          post :create, {:moderador => valid_attributes}, valid_session
        }.to change(Moderador, :count).by(1)
      end

      it "assigns a newly created moderador as @moderador" do
        post :create, {:moderador => valid_attributes}, valid_session
        assigns(:moderador).should be_a(Moderador)
        assigns(:moderador).should be_persisted
      end

      it "redirects to the created moderador" do
        post :create, {:moderador => valid_attributes}, valid_session
        response.should redirect_to(Moderador.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved moderador as @moderador" do
        # Trigger the behavior that occurs when invalid params are submitted
        Moderador.any_instance.stub(:save).and_return(false)
        post :create, {:moderador => { "nome" => "invalid value" }}, valid_session
        assigns(:moderador).should be_a_new(Moderador)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Moderador.any_instance.stub(:save).and_return(false)
        post :create, {:moderador => { "nome" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested moderador" do
        moderador = Moderador.create! valid_attributes
        # Assuming there are no other moderadors in the database, this
        # specifies that the Moderador created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Moderador.any_instance.should_receive(:update_attributes).with({ "nome" => "MyString" })
        put :update, {:id => moderador.to_param, :moderador => { "nome" => "MyString" }}, valid_session
      end

      it "assigns the requested moderador as @moderador" do
        moderador = Moderador.create! valid_attributes
        put :update, {:id => moderador.to_param, :moderador => valid_attributes}, valid_session
        assigns(:moderador).should eq(moderador)
      end

      it "redirects to the moderador" do
        moderador = Moderador.create! valid_attributes
        put :update, {:id => moderador.to_param, :moderador => valid_attributes}, valid_session
        response.should redirect_to(moderador)
      end
    end

    describe "with invalid params" do
      it "assigns the moderador as @moderador" do
        moderador = Moderador.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Moderador.any_instance.stub(:save).and_return(false)
        put :update, {:id => moderador.to_param, :moderador => { "nome" => "invalid value" }}, valid_session
        assigns(:moderador).should eq(moderador)
      end

      it "re-renders the 'edit' template" do
        moderador = Moderador.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Moderador.any_instance.stub(:save).and_return(false)
        put :update, {:id => moderador.to_param, :moderador => { "nome" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested moderador" do
      moderador = Moderador.create! valid_attributes
      expect {
        delete :destroy, {:id => moderador.to_param}, valid_session
      }.to change(Moderador, :count).by(-1)
    end

    it "redirects to the moderadors list" do
      moderador = Moderador.create! valid_attributes
      delete :destroy, {:id => moderador.to_param}, valid_session
      response.should redirect_to(moderadors_url)
    end
  end

end
