require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PedidosController do

  # This should return the minimal set of attributes required to create a valid
  # Pedido. As you add validations to Pedido, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "datapedido" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PedidosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all pedidos as @pedidos" do
      pedido = Pedido.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pedidos).should eq([pedido])
    end
  end

  describe "GET show" do
    it "assigns the requested pedido as @pedido" do
      pedido = Pedido.create! valid_attributes
      get :show, {:id => pedido.to_param}, valid_session
      assigns(:pedido).should eq(pedido)
    end
  end

  describe "GET new" do
    it "assigns a new pedido as @pedido" do
      get :new, {}, valid_session
      assigns(:pedido).should be_a_new(Pedido)
    end
  end

  describe "GET edit" do
    it "assigns the requested pedido as @pedido" do
      pedido = Pedido.create! valid_attributes
      get :edit, {:id => pedido.to_param}, valid_session
      assigns(:pedido).should eq(pedido)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pedido" do
        expect {
          post :create, {:pedido => valid_attributes}, valid_session
        }.to change(Pedido, :count).by(1)
      end

      it "assigns a newly created pedido as @pedido" do
        post :create, {:pedido => valid_attributes}, valid_session
        assigns(:pedido).should be_a(Pedido)
        assigns(:pedido).should be_persisted
      end

      it "redirects to the created pedido" do
        post :create, {:pedido => valid_attributes}, valid_session
        response.should redirect_to(Pedido.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pedido as @pedido" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pedido.any_instance.stub(:save).and_return(false)
        post :create, {:pedido => { "datapedido" => "invalid value" }}, valid_session
        assigns(:pedido).should be_a_new(Pedido)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pedido.any_instance.stub(:save).and_return(false)
        post :create, {:pedido => { "datapedido" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pedido" do
        pedido = Pedido.create! valid_attributes
        # Assuming there are no other pedidos in the database, this
        # specifies that the Pedido created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pedido.any_instance.should_receive(:update_attributes).with({ "datapedido" => "MyString" })
        put :update, {:id => pedido.to_param, :pedido => { "datapedido" => "MyString" }}, valid_session
      end

      it "assigns the requested pedido as @pedido" do
        pedido = Pedido.create! valid_attributes
        put :update, {:id => pedido.to_param, :pedido => valid_attributes}, valid_session
        assigns(:pedido).should eq(pedido)
      end

      it "redirects to the pedido" do
        pedido = Pedido.create! valid_attributes
        put :update, {:id => pedido.to_param, :pedido => valid_attributes}, valid_session
        response.should redirect_to(pedido)
      end
    end

    describe "with invalid params" do
      it "assigns the pedido as @pedido" do
        pedido = Pedido.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pedido.any_instance.stub(:save).and_return(false)
        put :update, {:id => pedido.to_param, :pedido => { "datapedido" => "invalid value" }}, valid_session
        assigns(:pedido).should eq(pedido)
      end

      it "re-renders the 'edit' template" do
        pedido = Pedido.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pedido.any_instance.stub(:save).and_return(false)
        put :update, {:id => pedido.to_param, :pedido => { "datapedido" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pedido" do
      pedido = Pedido.create! valid_attributes
      expect {
        delete :destroy, {:id => pedido.to_param}, valid_session
      }.to change(Pedido, :count).by(-1)
    end

    it "redirects to the pedidos list" do
      pedido = Pedido.create! valid_attributes
      delete :destroy, {:id => pedido.to_param}, valid_session
      response.should redirect_to(pedidos_url)
    end
  end

end
